name: mongol
description: This package provides Flutter widgets to display vertical Mongolian.
version: 0.3.1
author: Suragch <studymongolian@gmail.com>
homepage: https://github.com/suragch/mongol

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: MenksoftQagan
      fonts:
        - asset: lib/fonts/MQG8F02.ttf

